# Generated by Django 4.2.1 on 2023-06-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='brand',
        ),
    ]
