# Generated by Django 4.2.1 on 2023-06-08 13:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_seller_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
