# Generated by Django 4.2.1 on 2023-07-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('stock', models.BooleanField(default=True)),
                ('property_value', models.ManyToManyField(to='product.propertyvalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variants')),
            ],
            options={
                'verbose_name_plural': 'Options',
            },
        ),
    ]
