# Generated by Django 4.2.1 on 2023-07-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_variants_property_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantoption', to='product.variants'),
        ),
    ]
