# Generated by Django 4.2.1 on 2023-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
