# Generated by Django 4.2.1 on 2023-06-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress2',
            new_name='address2',
        ),
    ]
