"""
Django settings for blahite project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b^h&(dlxextog0ztcmw9xa77bt@e32&uo09zxxg-)8ax7n43tc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  


# ALLOWED_HOSTS = ['www.blahite.pl',
#                  'api.blahite.pl',
#                  'https://api.blahite.pl',
#                  'http://64.226.92.57',
#                  'https://64.226.92.57',
#                  'http://api.blahite.pl',
#                  'http://localhost:3000',
#                  'https://localhost:3000',
#                  'http://www.blahite.pl',
#                  'https://www.blahite.pl',
#                  'http://blahite.pl',
#                  'https://blahite.pl',]

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #custom
    'rest_framework_simplejwt',
    'corsheaders',
    'core.apps.CoreConfig',
    'product.apps.ProductConfig',
    'accounts.apps.AccountsConfig',
    'rest_framework',
    'ckeditor',
    'mptt',
    'django_cleanup.apps.CleanupConfig',
    'drf_yasg',




]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'ProductImagesCK/'
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}



SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = ['https://api.blahite.pl',
                        'http://64.226.92.57',
                        'https://64.226.92.57',
                        'http://api.blahite.pl',
                        'http://localhost:3000',
                        'https://localhost:3000',
                        'http://www.blahite.pl',
                        'https://www.blahite.pl',
                        'http://blahite.pl',
                        'https://blahite.pl',
                        ]


CORS_ALLOWED_ORIGINS = ['https://api.blahite.pl',
                        'http://64.226.92.57',
                        'https://64.226.92.57',
                        'http://api.blahite.pl',
                        'http://localhost:3000',
                        'https://localhost:3000',
                        'http://www.blahite.pl',
                        'https://www.blahite.pl',
                        'http://blahite.pl',
                        'https://blahite.pl',
                        ]
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

ROOT_URLCONF = 'blahite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blahite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB','blahite'),
        'USER': os.environ.get('POSTGRES_USER','isro'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD','isro'),
        'HOST': os.environ.get('POSTGRES_HOST','localhost'),
        'PORT': os.environ.get('POSTGRES_PORT','5432'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'accounts.User' 



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "accounts.api.serializers.JWTLoginSerializers",
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# if DEBUG:
#     STATICFILES_DIRS = [
#         BASE_DIR / 'static',
#     ]
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'blahitenoreply@gmail.com'
EMAIL_HOST_PASSWORD = 'bpivzkselrrvdcmy'
# esil parol digitalOcean4488